yiiAPP/frontend/models/Message.php
<?php

namespace frontend\models;

use Yii;
use common\models\User;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "message".
 *
 * @property integer $id
 * @property integer $sender_user_id
 * @property integer $receiver_user_id
 * @property string $message_text
 * @property string $created_at
 * @property string $updated_at
 *
 * @property User $receiverUser
 * @property User $senderUser
 */
class Message extends \yii\db\ActiveRecord
{

    const EVENT_MESSAGE_SENT = 'message-sent';
    const EVENT_MESSAGE_BADWORDS_DENIED='message-badwords-denied';

    public $username;

    //initialize the events 
    public function init(){

        // attach the events for logging 
        $this->on(self::EVENT_MESSAGE_SENT, [$this, 'logEventMessage']);
        $this->on(self::EVENT_MESSAGE_BADWORDS_DENIED, [$this, 'logEventMessage']);
        return parent::init();
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sender_user_id', 'receiver_user_id', 'message_text',], 'required'],
            [['sender_user_id', 'receiver_user_id','isred'], 'integer'],
            [['message_text'], 'string'],
            
            ['username', 'filter', 'filter' => 'trim'],
            ['username', 'required'],
            ['username', 'exist', 'targetClass' => '\common\models\User', 'targetAttribute' => 'username','message' => 'This username does not exist.'],
            [['created_at', 'updated_at'], 'safe'],

        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    \yii\db\ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => function() { return date("Y-m-d H:i:s"); },
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sender_user_id' => 'Sender User ID',
            'receiver_user_id' => 'Receiver User ID',
            'message_text' => 'Message Text',
            'isred'=> 'Is Red',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReceiverUser()
    {
        return $this->hasOne(User::className(), ['id' => 'receiver_user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSenderUser()
    {
        return $this->hasOne(User::className(), ['id' => 'sender_user_id']);
    }

    public function logEventMessage($event){
      Yii::info('recived message event for logging : '.$event->name);
    }
}

yiiAPP/frontend/controllers/MessageController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Message;
use frontend\models\MessageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
use yii\helpers\Url;
use common\models\BadwordsfilterSearch;

/**
 * MessageController implements the CRUD actions for Message model.
 */
class MessageController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),  
                'only' => ['delete'],              
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_USER],
                    ],                 
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Message models.
     * @return mixed
     */
    public function actionIndex()
    {
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        $searchModel = new MessageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=5;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,'count'=>$count,
        ]);
    }

    public function actionSent()
    {
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        $searchModel = new MessageSearch();
        $dataProvider = $searchModel->searchsentmessage(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=5;

        return $this->render('sent', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'count'=>$count,
        ]);
    }

    /**
     * Displays a single Message model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        
        $update=Yii::$app->db->createCommand()
        ->update('message', ['isred' => 1], 'id ="'.$id.'"')
        ->execute();
        $data = User::findOne($id);
        $model=$this->findModel($id);
        $user = User::find()->where('id = :userid', [':userid' =>$model->sender_user_id]) ->one();
        $userreceiver = User::find()->where('id = :userid', [':userid' =>$model->receiver_user_id]) ->one();

        return $this->render('view', [
            'model' => $model,
            'data' =>$data, 'count'=>$count,'user'=>$user,'userreceiver'=>$userreceiver,
        ]);
    }

    /**
     * Creates a new Message model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Message();
        $user = new User();
        //notification count 
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        if($id != null)
        {
            $user = User::find('username')->where('id = :userid', [':userid' => $id]) ->one();
        }
        $model->sender_user_id = Yii::$app->user->identity->id;

        if ($model->load(Yii::$app->request->post())) {
           
            $data = User::findOne(['username'=>$model->username]);
            if($data!=null && $data->id>0)
            $model->receiver_user_id= $data->id;        
            if($model->receiver_user_id==$model->sender_user_id)
                throw new \yii\web\HttpException(500, 'you cannot send the message to yourself');
            
            // serach the message for any bad words filter 
            $searchModelBadwords = new BadwordsfilterSearch();
            $dataProviderBadwords = $searchModelBadwords->fulltextsearch($model->message_text);

            // has bad words and user dont have permission to send messages throw an error 
            if($dataProviderBadwords->getTotalCount() > 0 && ! Yii::$app->user->can('allowBadwordsInMessage')){
                // log events 
                $model->trigger(Message::EVENT_MESSAGE_BADWORDS_DENIED); 
                throw new \yii\web\HttpException(403, 'You cannot send the message with bad words ');
            }
           
            if($model->save())
            {   
                // log events 
                $model->trigger(Message::EVENT_MESSAGE_SENT); 
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else
            {
                $tousername = User::find('username')->where('id = :userid', [':userid' => $data->id]) ->one();
                if($tousername)
                    $tousername=$tousername->username;
                else
                    $tousername=null;
                // $tousername="s";
                return $this->render('create', [
                    'model' => $model,'count'=>$count,'tousername'=>$tousername,
                ]);
            }             
            
        } else {
            $model->username=$user->username;
            $tousername = User::find('username')->where('id = :userid', [':userid' => $id]) ->one();       
            if($tousername)
                $tousername=$tousername->username;
            else
                $tousername=null;
            return $this->render('create', [
                'model' => $model,'count'=>$count,'tousername'=>$tousername,
            ]);
        }
    }


    /**
     * Deletes an existing Message model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }
    

    /**
     * Finds the Message model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Message the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Message::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }  

}

yiiAPP/frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use common\models\User;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Session;
use yii\web\Response;
use \yii\db\Query;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [                    
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }    

    public function actionGetNotificationsMessages($authkey=0)
     {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $authkey=isset($_REQUEST['authkey']) ? $_REQUEST['authkey'] : 0;
                    
             if ($user_id=User::validateAjaxAuth($authkey)) {

                $user=User::findOne(['id'=>$user_id]);
                $message=array();
                
                if (Yii::$app->request->isPost) {
                    
                    
                     // select * from messages where receiver_user_id=1 and (sent_at=recieved_at) order by id DESC limit 10 ;
                    $query = (new Query())
                        // ->select('count(id)') 
                        ->from(['message'])
                        ->where( ' ( receiver_user_id=:useridto ) and  (isred=0) ',[':useridto'=>$user->id])
                        ->orderBy(['id'=>SORT_DESC]);
                    $count=$query->count();                         
                    $res = array(
                            'message'   => array('count'=>$count) ,
                            'status' =>200,
                        );
                                            
                }else
                {
                    throw new \yii\web\HttpException(500, ' Make Post Call to get Messages  Noftiications ');   
                }

                return $res;
            }else
            {
                throw new \yii\web\HttpException(403, ' Damm you are not allowed perform this action'); 
            }

        }
        
        //message auto fill 
        public function actionAutofillUsers($authkey=0) {

            Yii::$app->response->format = Response::FORMAT_JSON;
            $authkey=isset($_REQUEST['authkey']) ? $_REQUEST['authkey'] : 0;
                    
             if ($user_id=User::validateAjaxAuth($authkey)) {

                $user=User::findOne(['id'=>$user_id]);
                $message=array();
                
                if (Yii::$app->request->isPost) {
                    
                    $pageno=isset($_REQUEST['pageno']) ? $_REQUEST['pageno'] : 0 ;
                    $like=isset($_REQUEST['like']) ? trim($_REQUEST['like']) : "" ;
                    
                    if(is_null(trim($pageno)))
                    {
                        throw new UserException(" Page No cannot be Null  ");
                    }

                    if (!$this->isonlynumbers($pageno)) {
                        throw new UserException(" Page No should be number only ");
                    }   

                    

                    $query = (new Query()) ->select(['user.username as id','user.username as name'])
                        ->from( "user ");


                    // $query->where(['like','Tprofile.first_name','kar']);
                    if($like!=""){
                        $query->where(['like','user.username',$like]);
                        // $query->where(['or',['or' ,['like','user_profile.first_name',$like],['like','user_profile.last_name',$like]]]); 
                    }else {
                        $query->where(['not', ['id' => $user->id]]);
                    }   
                    // 
                    
                    // $query->leftJoin('user_profile','user_profile.user_id=user.id');

                    $command = $query->createCommand()->getSql();

                                     
                    $pagesize = 20;
                    $totalrowcount=$query->count();
                    if(!$query->exists())
                    {
                        throw new UserException(" No users conected  ");
                        
                    }

                    $totalrowcount = isset($totalrowcount) ? (int) $totalrowcount : 0;
                    // var_dump($totalrowcount);
                    $totalpagecount = (int) round($totalrowcount / $pagesize);
                    $offset = $pageno * $pagesize;
                    $offset = $offset < 0 ? 0 : $offset;
                    $offset += 1;
                    $limit = $pagesize;

                    $query->limit($limit);
                    if($pageno!=0)
                    {
                        $query->offset($offset);    
                    }
                    $command = $query->createCommand()->getSql();
                    $models=$query->all();
                

                    $res = array(
                              'message'   => array('data'=>$models,'totalpagecount'=>$totalpagecount,'pageno'=>$pageno) ,
                            'status' =>200,
                        );
                    // 'limit' => $limit, 'offset' => $offset)

                                    
                }else
                {
                    throw new \yii\web\HttpException(500, ' Make Post Call to get Messages  '); 
                }

                return $res;
            }else
            {
                throw new \yii\web\HttpException(403, ' Damm you are not allowed perform this action'); 
            }
        }

        /**
        * Validate that the value is an integer. 
        * @param mixed val 
        * @return true or false
        */
        public static function isonlynumbers($value)
        {
            if(preg_match('/[^0-9]/',$value))
                return false;
            else
                return true;
        }
}

yiiAPP/frontend/views/message/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\User;
use yii\web\View;
use yii\helpers\Url;
use yii\jui\JuiAsset;
JuiAsset::register($this);

/* @var $this yii\web\View */
/* @var $model frontend\models\Message */
/* @var $form yii\widgets\ActiveForm */
?>
 <?php

    $dataList=ArrayHelper::map(User::find()->asArray()->all(), 'username','username');
   /* <?=$form->field($model, 'username')->label('Send To ')->dropDownList($dataList, 
         ['prompt'=>'-Choose a username-']) ?> */

?>
<?php $this->registerJsFile('//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js',['depends' => [\yii\web\JqueryAsset::className()]]); ?> 
<?php $this->registerJsFile('//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/additional-methods.min.js',['depends' => [\yii\web\JqueryAsset::className()]]); ?> 

<div class="message-form">

    <?php $form = ActiveForm::begin(); ?>
    <?php if($model->username== null || $model->hasErrors('username'))
    {   
        ?>
        
        
        <?=Html::activeHiddenInput($model, 'username') ?>
        <?php if($model->hasErrors('username')) { ?>
        <div class="form-group  required has-error" id="newmessageusernamemodalform">
        <label class="control-label" for="message-name">Send To </label>
                <input type="text" class="form-control" id="newmessageusernamemodal" placeholder="Enter the name Slowly">
            <div id="newmessageusernamemodalhelp" class="help-block">This user does not exist.</div>
        </div>
        <?php }else { ?>
            <div class="form-group  required ">
                <label class="control-label" for="message-name">Send To </label>
                <input type="text" name="message-name" class="form-control" id="newmessageusernamemodal" placeholder="Enter the name Slowly">
                
            </div>
        <?php } ?>


    <?php }
    else
    {
        // $tousername ="s";
        if($tousername)
        {
            echo '<small>To: '.$tousername.'</small>';
        } 
        ?>

        <?=Html::activeHiddenInput($model, 'username') ?>
    <?php } ?>
    
    <?= $form->field($model, 'message_text')->label('Message')->textarea(['rows' => 6, 'placeholder'=>'Message Body']) ?>
<style type="text/css">
    #message-message_text {
        color: black;
    }
</style>
    <div class="row">
        <div class="col-lg-12">
            <div class="btn-toolbar message-controls" role="toolbar">
                <div class="pull-right">
                    <button class="btn btn-transparent"> <span>Send</span> <i class="fa fa-send"></i> </button>
                </div>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php $this->registerJs('$( document ).ready(function() {

     // console.log("hello");
  
        String.prototype.trunc =
            function(n, useWordBoundary) {
                var toLong = this.length > n,
                    s_ = toLong ? this.substr(0, n - 1) : this;
                s_ = useWordBoundary && toLong ? s_.substr(0, s_.lastIndexOf(" ")) : s_;
                return toLong ? s_ + "&hellip;" : s_;
            };
             $( "#newmessageusernamemodal" ).autocomplete({
            _renderItem:function(ul,item){
                return $( "<li>" )
                         .attr( "data-id", item.id )
                         .append( item.label )
                         .appendTo( ul );

                    },
            select: function( event, ui ) {
                $( "#newmessageusernamemodal" ).val(ui.item.label);
                $( "#message-username" ).val(ui.item.id);


            },
            change: function(event,ui)
                    {
                        if (ui.item==null)
                        {
                            $("#newmessageusernamemodal").val("");
                            $( "#message-username" ).val(0);
                            $("#newmessageusernamemodal").focus();
                        }
                    },
            source: function( request, response ) {
                pageno=0;
                var fd = new FormData();
                //input the from data please follow the order as below only 
                fd.append("authkey", $("#authkey").html());
                fd.append("pageno", pageno);
                fd.append("like",request.term.trim());

                var re = new RegExp(/^[a-zA-Z0-9\s]+$/);
                    if(!re.test(request.term)) {
                        $( "#newmessageusernamemodal" ).val("");
                        $( "#message-username" ).val(0);
                        responseautocomplete(); 
                        return;
                    } 
                var responseautocomplete=response;
                $.ajax({
                    type: "POST",
                    url: "'.Url::toRoute("site/autofill-users").'",
                    dataType: "json",
                    processData: false, // Not supported with Trigger
                    contentType: false, // Not supported with Trigger
                    data: fd,
                    error: function(response) {
                        responseautocomplete();
                        $( "#message-username" ).val(0);
                    },
                    success: function(response) {
                        if(response.status==200)
                        {
                            var tags = [];
                            for (var i = response.message.data.length - 1; i >= 0; i--) {
                                tags[i]={ label: response.message.data[i].name , value: response.message.data[i].name , id:response.message.data[i].id , image : response.message.data[i].img };
                            }
                            responseautocomplete(tags);

                        }else
                        {
                            responseautocomplete(); 
                            $( "#message-username" ).val(0);
                        }
                        
                    }

                });
               
                }
        });
    $("#newmessageusernamemodal").change(function(event){
        if(String($(this).val).trunc()=="")
        {
          $( "#message-username" ).val(0);
          $("#newmessageusernamemodalform" ).addClass("has-error");
          $("#newmessageusernamemodalhelp").html("User Name required ");

        }
        $( "#newmessageusernamemodalform" ).removeClass("has-error");
        $("#newmessageusernamemodalhelp").html("");

    });

    // $(".form-group.field-message-username").hide();

     jQuery.validator.setDefaults({        
      highlight: function(element) {
            jQuery(element).closest(".form-group").addClass("has-error");
            // jQuery(element).closest(".form-group").removeClass("has-success");
        },
        unhighlight: function(element) {
            jQuery(element).closest(".form-group").removeClass("has-error");
            // jQuery(element).closest(".form-group").addClass("has-success");
        },
        errorElement: "div",
        errorClass: "help-block",
        errorPlacement: function(error, element) {
            console.log(element.attributes);
            if(element.parent(".input-group").length) {
                error.insertAfter(element.parent());
            } else {
                error.insertAfter(element);
            }
        }
    });

    $("#w0").validate({
      //   submitHandler: function(form) {
      //   // form.submit();
      // },
      ignore: "not:hidden",
      rules: {        
        "message-name": { 
            required : true,
        },
        "Message[message_text]": { 
            required : true,
        },

      },
      messages :{
        "message-name" : {
            required :"  Please Enter Username  "
        },  
        "Message[message_text]": { 
            required : "Message is required ",
        },   
      }
    });
           }); ',View::POS_READY,'sendmessage-js'); ?> 

yiiAPP/frontend/views/message/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\MessageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="message-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'sender_user_id') ?>

    <?= $form->field($model, 'receiver_user_id') ?>

    <?= $form->field($model, 'message_text') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yiiAPP/frontend/views/message/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use frontend\components\CustomPagination;
use frontend\models\Message;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\MessageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Create Message';
$this->params['breadcrumbs'][] = $this->title;
if(!isset($tousername))
    $tousername=null;
?>

        <!-- start here -->
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">Create Message</h4>
                <p>
                Donec elit libero, sodales nec, volutpat a, suscipit non, turpis. Suspendisse enim turpis, dictum sed, iaculis a, condimentum nec, nisi. Nunc sed turpis. Vivamus merfio ljudyio hferhu euismod mauris. Curabitur nisi.
                </p>
                <hr>
            </div>
        </div>
        <div class="row">
            <!-- Left sidebar -->
            <div class="col-lg-3 col-md-4">
                <div class="panel panel-default p-0  m-t-20">
                    <div class="list-group mail-list">
                        <a href="<?= Url::to(['create','id'=>""])?>" class="list-group-item no-border active"><i class="fa fa-pencil m-r-5"></i> &nbsp;&nbsp;Compose  </a>
                        <a href="<?= Url::to(['index'])?>" class="list-group-item no-border "><i class="fa fa-download m-r-5"></i> &nbsp;&nbsp; Inbox <b> <?= Html::encode('('.$count.')') ?></b></a>
                        <!-- <a href="#" class="list-group-item no-border"><i class="fa fa-star-o m-r-5"></i> &nbsp;&nbsp; Starred</a> -->
                        <!-- <a href="#" class="list-group-item no-border"><i class="fa fa-file-text-o m-r-5"></i> &nbsp;&nbsp; Draft <b>(20)</b></a> -->
                        <a href="<?= Url::to(['sent'])?>" class="list-group-item no-border" ><i class="fa fa-paper-plane-o m-r-5"></i> &nbsp;&nbsp; Sent Mail</a>
                        <!-- <a href="#" class="list-group-item no-border"><i class="fa fa-trash-o m-r-5"></i> &nbsp;&nbsp; Trash <b>(354)</b></a> -->
                    </div>
                </div>
            </div>
             <!-- End Left sidebar -->
            <!-- Right Sidebar -->
            <div class="col-md-8 col-lg-9">
                <div class="panel panel-default m-t-20">
                    <div class="panel-body p-t-30">
                         <?= $this->render('_form', [
					        'model' => $model,'tousername'=>$tousername,
					    ]) ?>
                    </div>
                    <!-- panel -body -->
                </div>
                <!-- panel -->
            </div>
            <!-- end Col-9 -->
        </div>

yiiAPP/frontend/views/message/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Message */

$this->title = 'Update Message: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Messages', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="message-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>