yiiAPP/frontend/controllers/MessageController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Message;
use frontend\models\MessageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
use yii\helpers\Url;
use common\models\BadwordsfilterSearch;

/**
 * MessageController implements the CRUD actions for Message model.
 */
class MessageController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),  
                'only' => ['delete'],              
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_USER],
                    ],                 
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Message models.
     * @return mixed
     */
    public function actionIndex()
    {
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        $searchModel = new MessageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=5;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,'count'=>$count,
        ]);
    }

    public function actionSent()
    {
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        $searchModel = new MessageSearch();
        $dataProvider = $searchModel->searchsentmessage(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=5;

        return $this->render('sent', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'count'=>$count,
        ]);
    }

    /**
     * Displays a single Message model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        
        $update=Yii::$app->db->createCommand()
        ->update('message', ['isred' => 1], 'id ="'.$id.'"')
        ->execute();
        $data = User::findOne($id);
        $model=$this->findModel($id);
        $user = User::find()->where('id = :userid', [':userid' =>$model->sender_user_id]) ->one();
        $userreceiver = User::find()->where('id = :userid', [':userid' =>$model->receiver_user_id]) ->one();

        return $this->render('view', [
            'model' => $model,
            'data' =>$data, 'count'=>$count,'user'=>$user,'userreceiver'=>$userreceiver,
        ]);
    }

    /**
     * Creates a new Message model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Message();
        $user = new User();
        //notification count 
        $count = Message::find()->where(['isred' => 0, 'receiver_user_id' => Yii::$app->user->id])->count();
        if($id != null)
        {
            $user = User::find('username')->where('id = :userid', [':userid' => $id]) ->one();
        }
        $model->sender_user_id = Yii::$app->user->identity->id;

        if ($model->load(Yii::$app->request->post())) {
           
            $data = User::findOne(['username'=>$model->username]);
            if($data!=null && $data->id>0)
            $model->receiver_user_id= $data->id;        
            if($model->receiver_user_id==$model->sender_user_id)
                throw new \yii\web\HttpException(500, 'you cannot send the message to yourself');
            
            // serach the message for any bad words filter 
            $searchModelBadwords = new BadwordsfilterSearch();
            $dataProviderBadwords = $searchModelBadwords->fulltextsearch($model->message_text);

            // has bad words and user dont have permission to send messages throw an error 
            if($dataProviderBadwords->getTotalCount() > 0 && ! Yii::$app->user->can('allowBadwordsInMessage')){
                // log events 
                $model->trigger(Message::EVENT_MESSAGE_BADWORDS_DENIED); 
                throw new \yii\web\HttpException(403, 'You cannot send the message with bad words ');
            }
           
            if($model->save())
            {   
                // log events 
                $model->trigger(Message::EVENT_MESSAGE_SENT); 
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else
            {
                $tousername = User::find('username')->where('id = :userid', [':userid' => $data->id]) ->one();
                if($tousername)
                    $tousername=$tousername->username;
                else
                    $tousername=null;
                // $tousername="s";
                return $this->render('create', [
                    'model' => $model,'count'=>$count,'tousername'=>$tousername,
                ]);
            }             
            
        } else {
            $model->username=$user->username;
            $tousername = User::find('username')->where('id = :userid', [':userid' => $id]) ->one();       
            if($tousername)
                $tousername=$tousername->username;
            else
                $tousername=null;
            return $this->render('create', [
                'model' => $model,'count'=>$count,'tousername'=>$tousername,
            ]);
        }
    }


    /**
     * Deletes an existing Message model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }
    

    /**
     * Finds the Message model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Message the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Message::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }  

}

yiiAPP/frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use common\models\User;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Session;
use yii\web\Response;
use \yii\db\Query;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [                    
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }    

    public function actionGetNotificationsMessages($authkey=0)
     {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $authkey=isset($_REQUEST['authkey']) ? $_REQUEST['authkey'] : 0;
                    
             if ($user_id=User::validateAjaxAuth($authkey)) {

                $user=User::findOne(['id'=>$user_id]);
                $message=array();
                
                if (Yii::$app->request->isPost) {
                    
                    
                     // select * from messages where receiver_user_id=1 and (sent_at=recieved_at) order by id DESC limit 10 ;
                    $query = (new Query())
                        // ->select('count(id)') 
                        ->from(['message'])
                        ->where( ' ( receiver_user_id=:useridto ) and  (isred=0) ',[':useridto'=>$user->id])
                        ->orderBy(['id'=>SORT_DESC]);
                    $count=$query->count();                         
                    $res = array(
                            'message'   => array('count'=>$count) ,
                            'status' =>200,
                        );
                                            
                }else
                {
                    throw new \yii\web\HttpException(500, ' Make Post Call to get Messages  Noftiications ');   
                }

                return $res;
            }else
            {
                throw new \yii\web\HttpException(403, ' Damm you are not allowed perform this action'); 
            }

        }
        
        //message auto fill 
        public function actionAutofillUsers($authkey=0) {

            Yii::$app->response->format = Response::FORMAT_JSON;
            $authkey=isset($_REQUEST['authkey']) ? $_REQUEST['authkey'] : 0;
                    
             if ($user_id=User::validateAjaxAuth($authkey)) {

                $user=User::findOne(['id'=>$user_id]);
                $message=array();
                
                if (Yii::$app->request->isPost) {
                    
                    $pageno=isset($_REQUEST['pageno']) ? $_REQUEST['pageno'] : 0 ;
                    $like=isset($_REQUEST['like']) ? trim($_REQUEST['like']) : "" ;
                    
                    if(is_null(trim($pageno)))
                    {
                        throw new UserException(" Page No cannot be Null  ");
                    }

                    if (!$this->isonlynumbers($pageno)) {
                        throw new UserException(" Page No should be number only ");
                    }   

                    

                    $query = (new Query()) ->select(['user.username as id','user.username as name'])
                        ->from( "user ");


                    // $query->where(['like','Tprofile.first_name','kar']);
                    if($like!=""){
                        $query->where(['like','user.username',$like]);
                        // $query->where(['or',['or' ,['like','user_profile.first_name',$like],['like','user_profile.last_name',$like]]]); 
                    }else {
                        $query->where(['not', ['id' => $user->id]]);
                    }   
                    // 
                    
                    // $query->leftJoin('user_profile','user_profile.user_id=user.id');

                    $command = $query->createCommand()->getSql();

                                     
                    $pagesize = 20;
                    $totalrowcount=$query->count();
                    if(!$query->exists())
                    {
                        throw new UserException(" No users conected  ");
                        
                    }

                    $totalrowcount = isset($totalrowcount) ? (int) $totalrowcount : 0;
                    // var_dump($totalrowcount);
                    $totalpagecount = (int) round($totalrowcount / $pagesize);
                    $offset = $pageno * $pagesize;
                    $offset = $offset < 0 ? 0 : $offset;
                    $offset += 1;
                    $limit = $pagesize;

                    $query->limit($limit);
                    if($pageno!=0)
                    {
                        $query->offset($offset);    
                    }
                    $command = $query->createCommand()->getSql();
                    $models=$query->all();
                

                    $res = array(
                              'message'   => array('data'=>$models,'totalpagecount'=>$totalpagecount,'pageno'=>$pageno) ,
                            'status' =>200,
                        );
                    // 'limit' => $limit, 'offset' => $offset)

                                    
                }else
                {
                    throw new \yii\web\HttpException(500, ' Make Post Call to get Messages  '); 
                }

                return $res;
            }else
            {
                throw new \yii\web\HttpException(403, ' Damm you are not allowed perform this action'); 
            }
        }

        /**
        * Validate that the value is an integer. 
        * @param mixed val 
        * @return true or false
        */
        public static function isonlynumbers($value)
        {
            if(preg_match('/[^0-9]/',$value))
                return false;
            else
                return true;
        }
}

yiiAPP/frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;
use yii\helpers\Url;
AppAsset::register($this);
$authkey="dummyNull";
if(!Yii::$app->user->isGuest) {
    $user = \common\models\User::findOne(['id' => Yii::$app->user->id]);
    $authkey=$user->auth_key;  
}
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Bananabandy (User)',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-blue navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],       
    ];
    if (Yii::$app->user->isGuest) {       
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];      
    } else {       
         //message link
         $menuItems[] = '<li><a href="'.Url::toRoute('message/index').'" class="nav-btn messageshref"> Messages <span class="badge">0</span> </a></li>';
          $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    echo  '<span class="hidden" id="authkey">'.$authkey.'</span>';
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Bananabandy (User) <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>

<?php if(!Yii::$app->user->isGuest) { ?>
<script type="text/javascript">
    //message notification list 
    // http://localhost/WorkspaceAngle/defy/defy/frontend/web/index.php?r=ajax/get-notifications-messages
    $(document).ready(function() {
              function fetchmessagenotifications() {
                        //fetching chat heads 
                        var fd = new FormData();
                        //input the from data please follow the order as below only 
                        fd.append('authkey','<?php echo $authkey;?>');                        
                        $.ajax({
                            type: 'POST',
                            url: '<?=Url::toRoute('site/get-notifications-messages') ?>',
                            dataType: 'json',
                            processData: false, // Not supported with Trigger
                            contentType: false, // Not supported with Trigger
                            data: fd,
                            error: function(response) {
                                // console.log(response.responseText);
                                 console.log("error in fetch notifications");
                            },
                            success: function(response) {
                               
                                if(response.status=200)
                                {
                                   if(response.message.count > 0)
                                    $(".messageshref").html(" Messages <span class='badge'>"+response.message.count +"</span>");
                                   else
                                    $(".messageshref").html(" Messages ");

                                }
                            }

                        });
                    }                         

            var t;
            var timer_is_on = 0;

            function timedCount() {
               fetchmessagenotifications();
                t = setTimeout(function(){timedCount()}, 10000);
            }

            function doTimer() {
                if (!timer_is_on) {
                    timer_is_on = 1;
                    timedCount();
                }
            }

            function stopCount() {
                clearTimeout(t);
                timer_is_on = 0;
            }

            doTimer();

    });        
</script>
<?php } ?>
</body>
</html>
<?php $this->endPage() ?>